# Generated by Django 4.0.3 on 2022-03-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridients', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('price_for_measure', models.CharField(max_length=50)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('job_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.restarant')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('description', models.CharField(default='SOME STRING', max_length=500)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.autorisation')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_full', models.CharField(max_length=10)),
                ('name_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.menu')),
                ('name_waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restarantRayhonapp.personal')),
            ],
        ),
    ]
