# Generated by Django 4.0.3 on 2022-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarantRayhonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorisation',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
