# Generated by Django 4.0.3 on 2022-03-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restarantRayhonapp', '0002_autorisation_e_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telephone',
            field=models.CharField(max_length=25),
        ),
    ]
